### ISSUE TITLE
Datarace when using sync.WaitGroup

### ISSUE THREAD

**Issue by emacampolo** [moov-io/iso8583-connection#27] opened 2023-01-03 00:10 UTC
When running tests with data race enabled, some of them fail because they concurrently access wg.Wait and wg.Add in the Send() and Close() methods. To reproduce it, run `go test ./... -count=10 -race` (or any high count number since it is not deterministic)

Example for `TestClient_Send/ReadTimeoutHandler_called_after_ReadTimeout_elapses`

WARNING: DATA RACE
**Read at** 0x00c0004eeed8 by goroutine 3245:
  runtime.raceread()
      <autogenerated>:1 +0x10
  github.com/moov-io/iso8583-connection.(*Connection).Send()
      /Users/ecampolo/GoProjects/iso8583-connection/connection.go:311 +0x4c
  github.com/moov-io/iso8583-connection_test.TestClient_Send.func8.1()
      /Users/ecampolo/GoProjects/iso8583-connection/connection_test.go:481 +0x2a0
  github.com/moov-io/iso8583-connection.(*Connection).writeLoop.func1()
      /Users/ecampolo/GoProjects/iso8583-connection/connection.go:522 +0x44

**Previous write** at 0x00c0004eeed8 by goroutine 3226:
  runtime.racewrite()
      <autogenerated>:1 +0x10
  github.com/moov-io/iso8583-connection.(*Connection).close()
      /Users/ecampolo/GoProjects/iso8583-connection/connection.go:253 +0x30
  github.com/moov-io/iso8583-connection.(*Connection).Close()
      /Users/ecampolo/GoProjects/iso8583-connection/connection.go:279 +0x94
  github.com/moov-io/iso8583-connection_test.TestClient_Send.func8.5()
      /Users/ecampolo/GoProjects/iso8583-connection/connection_test.go:502 +0x34
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:476 +0x30
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1446 +0x188
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1493 +0x40

**Comment by alovak** [comment] 2023-01-03 20:13
I was not able to reproduce the reported issue. With provided command `go test ./... -count 10 -race` it timed out on my machine. With `-timeout 0` it never ended...

I also tried to run: 
`go test -race -count 100 -timeout 0 -run TestClient_Send/ReadTimeoutHandler_called_after_ReadTimeout_elapses`

without issues.


Looking at the code, I see the potential issue when we call `Close,` but some callbacks (ping, readtimeout) can make a call to `Send`. Most probably the issue is with the `Close` that is calling `wg.Wait()` and then `Send` calling`wg.Add(1)`. From the documentation for `func (wg *WaitGroup) Add(delta int)`:
> Note that calls with a positive delta that occur when the counter is zero must happen before a Wait.

But unfortunately, I can't confirm it :(

**Comment by adamdecaf** [comment] 2023-01-06 20:25
https://github.com/moov-io/iso8583-connection/pull/28 makes sense to me. If we can't reproduce this issue I think merging still makes sense.

**Comment by alovak** [comment] 2023-07-27 10:09
Closing as it seems that the issue was solved in https://github.com/moov-io/iso8583-connection/pull/28

**Closed as completed by alovak** 2023-07-27 10:09 UTC
Labels: bug, help wanted
